import { createFileRoute } from "@tanstack/react-router";
import { Award, Handshake, ScanLine } from "lucide-react";
import commercial from "../assets/commercial-finish.jpg.asset.json";
import { PageIntro, QuoteBand } from "../components/site-shell";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Floor 2 Frames Solutions" }, { name: "description", content: "Meet the finishing specialists behind premium residential and commercial spaces." },
  { property: "og:title", content: "About Floor 2 Frames Solutions" }, { property: "og:description", content: "Expert workmanship, reliable service and considered finishing solutions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutPage });

function AboutPage(){ return <><PageIntro eyebrow="Our standard" title="From the floor up, excellence in every detail.">Floor 2 Frames brings together technical expertise, premium materials and considered workmanship to create spaces with lasting impact.</PageIntro><section className="bg-ivory py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><img src={commercial.url} alt="Floor 2 Frames completed commercial interior" className="aspect-[4/5] w-full object-cover"/><div className="lg:px-12"><p className="eyebrow">Built around your space</p><h2 className="mt-5 font-display text-5xl leading-tight">A complete finishing partner.</h2><p className="mt-6 text-sm leading-8 text-muted-foreground">We work across residential, commercial and industrial environments, combining durable specifications with refined aesthetics. Every project is approached as a whole—from preparation and material selection to installation and the final edge.</p><p className="mt-5 text-sm leading-8 text-muted-foreground">The result is practical beauty: surfaces and frames that feel intentional, perform reliably and elevate everyday spaces.</p></div></div></section><section className="bg-charcoal py-20 text-ivory"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-3 lg:px-8">{[[Award,"Premium quality","We select fit-for-purpose materials and never compromise the finish."],[ScanLine,"Expert workmanship","Precision, preparation and close attention define every installation."],[Handshake,"Reliable service","Clear communication and accountable delivery from start to handover."]].map(([Icon,title,text])=>{const I=Icon as typeof Award; return <div key={title as string} className="border-t border-gold pt-7"><I className="text-gold"/><h3 className="mt-8 font-display text-3xl">{title as string}</h3><p className="mt-3 text-sm leading-7 text-ivory/55">{text as string}</p></div>})}</div></section><QuoteBand/></> }